# Generated by Django 4.2.30 on 2026-05-16 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("successful", "Successful"), ("declined", "Declined")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(max_length=80, unique=True)),
                ("provider", models.CharField(default="flutterwave", max_length=40)),
                ("checkout_url", models.URLField(blank=True)),
                ("provider_transaction_id", models.CharField(blank=True, max_length=80)),
                ("status_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
