# Generated by Django 4.2.30 on 2026-05-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in minor currency units (kobo/cents).'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('declined', 'Declined'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
