# Generated by Django 4.2.30 on 2026-08-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0015_audiouploadintent'),
        ('live_broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='agora_recording_resource_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='agora_recording_sid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='agora_recording_uid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='archived_testimony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_live_broadcast', to='testimonies.testimony'),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_broadcasts', to='testimonies.testimonycategory'),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='ended_reason',
            field=models.CharField(blank=True, choices=[('creator_ended', 'Creator Ended'), ('dropped', 'Dropped'), ('admin_terminated', 'Admin Terminated')], max_length=20),
        ),
        migrations.AddField(
            model_name='livebroadcast',
            name='recording_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('recording', 'Recording'), ('stopping', 'Stopping'), ('archived', 'Archived'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
