# Generated by Django 4.2.30 on 2026-08-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_broadcasts', '0002_livebroadcast_agora_recording_resource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='admin_termination_note',
            field=models.TextField(blank=True),
        ),
    ]
