# Generated by Django 4.2.30 on 2026-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_broadcasts', '0003_livebroadcast_admin_termination_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='livebroadcast',
            name='platform_ceiling_minutes_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
