# Generated by Django 4.2.30 on 2026-07-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_finalize_inspirational_picture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspirationalpicture',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
