# Generated by Django 4.2.30 on 2026-07-30 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_featuredhomepicture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptureReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripture_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='scripturereadreceipt',
            constraint=models.UniqueConstraint(fields=('user', 'read_date'), name='uniq_scripture_read_receipt_user_date'),
        ),
    ]
