# Generated by Django 4.2.30 on 2026-08-16 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0008_scripture_read_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_destination', models.CharField(blank=True, choices=[('giving', 'Giving screen'), ('submit_testimony', 'Submit a testimony'), ('external_url', 'External URL')], max_length=20)),
                ('cta_url', models.URLField(blank=True, help_text='Only used when cta_destination is external_url.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_promo_cards_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_promo_cards_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
