# Generated by Django 4.2.30 on 2026-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_homepromocard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepromocard',
            name='cta_destination',
            field=models.CharField(blank=True, choices=[('giving', 'Giving screen'), ('submit_testimony', 'Submit a testimony'), ('external_url', 'External URL'), ('referral_link', 'Referral link screen')], max_length=20),
        ),
    ]
