# Generated by Django 4.2.30 on 2026-05-16 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0004_testimony_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending_review', max_length=20),
        ),
        migrations.CreateModel(
            name='TestimonyModerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('archived', 'Archived'), ('auto_published', 'Auto Published')], max_length=32)),
                ('from_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimony_moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='testimonies.testimony')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
