# Generated by Django 4.2.30 on 2026-07-29 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0008_testimony_admin_filter_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='amen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimony',
            name='gives_me_hope_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimony',
            name='praying_for_you_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TestimonyReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('praying_for_you', 'Praying for you'), ('amen', 'Amen'), ('gives_me_hope', 'Gives me hope')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='testimonies.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='testimonyreaction',
            constraint=models.UniqueConstraint(fields=('user', 'testimony'), name='uniq_testimony_reaction_user_testimony'),
        ),
    ]
