# Generated by Django 4.2.30 on 2026-07-30 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0010_userfollowedcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='testimonies.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_watches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='testimonywatch',
            constraint=models.UniqueConstraint(fields=('user', 'testimony'), name='uniq_testimony_watch_user_testimony'),
        ),
    ]
