# Generated by Django 4.2.30 on 2026-07-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0011_testimonywatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='pull_quote',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
