# Generated by Django 4.2.30 on 2026-08-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0012_testimony_pull_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('translated_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_jobs', to='testimonies.testimony')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testimony', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_job', to='testimonies.testimony')),
            ],
        ),
        migrations.AddConstraint(
            model_name='translationjob',
            constraint=models.UniqueConstraint(fields=('testimony', 'language'), name='uniq_translation_job_per_language'),
        ),
    ]
