# Generated by Django 4.2.30 on 2026-08-23 22:11

import apps.testimonies.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0013_translationjob_transcriptionjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony_type',
            field=models.CharField(choices=[('written', 'Written'), ('video', 'Video'), ('audio', 'Audio')], default='written', max_length=20),
        ),
        migrations.CreateModel(
            name='AudioUploadPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('max_file_size_bytes', models.PositiveBigIntegerField(default=52428800)),
                ('max_duration_ms', models.PositiveIntegerField(default=900000)),
                ('allowed_content_types', models.JSONField(default=apps.testimonies.models.default_audio_content_types)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_audio_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
