# Generated by Django 4.2.30 on 2026-08-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0014_testimony_audio_url_testimony_duration_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.CharField(max_length=255)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('max_file_size_bytes', models.PositiveBigIntegerField()),
                ('max_duration_ms', models.PositiveIntegerField()),
                ('allowed_content_types', models.JSONField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_upload_intent', to='testimonies.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_upload_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'consumed_at', 'expires_at'], name='audio_intent_user_state_idx')],
            },
        ),
    ]
