# Generated by Django 4.2.30 on 2026-08-26 21:44

import apps.testimonies.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0015_audiouploadintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('max_file_size_bytes', models.PositiveBigIntegerField(default=209715200)),
                ('max_duration_ms', models.PositiveIntegerField(default=300000)),
                ('allowed_content_types', models.JSONField(default=apps.testimonies.models.default_video_content_types)),
                ('daily_limit', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_video_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='audiouploadpolicy',
            name='daily_limit',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='VideoUploadPolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('from_value', models.CharField(blank=True, max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_upload_policy_history_actions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='testimonies.videouploadpolicy')),
            ],
            options={
                'verbose_name_plural': 'video upload policy history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioUploadPolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('from_value', models.CharField(blank=True, max_length=255)),
                ('to_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_upload_policy_history_actions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='testimonies.audiouploadpolicy')),
            ],
            options={
                'verbose_name_plural': 'audio upload policy history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoUploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder', models.CharField(max_length=255)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('max_file_size_bytes', models.PositiveBigIntegerField()),
                ('max_duration_ms', models.PositiveIntegerField()),
                ('allowed_content_types', models.JSONField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_upload_intent', to='testimonies.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_upload_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'consumed_at', 'expires_at'], name='video_intent_user_state_idx')],
            },
        ),
    ]
