# Generated by Django 4.2.30 on 2026-08-05 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text="Amount in minor currency units (kobo/cents), matching Donation's convention.")),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_reference', models.CharField(help_text="Our own reference for the subscription's first charge only -- Flutterwave generates its own reference for each automatic renewal charge.", max_length=80, unique=True)),
                ('provider', models.CharField(default='flutterwave', max_length=40)),
                ('provider_plan_id', models.CharField(blank=True, max_length=40)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=80)),
                ('checkout_url', models.URLField(blank=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=80)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=80)),
                ('raw_payload', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_status_actions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'active', 'past_due'))), fields=('user',), name='one_non_terminal_subscription_per_user'),
        ),
    ]
