# Generated by Django 4.2.30 on 2026-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='User asked to cancel -- status stays ACTIVE/PAST_DUE (access continues) until current_period_end passes, rather than clawing back time already paid for. No further renewal charge will occur.'),
        ),
    ]
