# Generated by Django 4.2.30 on 2026-08-07 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0002_subscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('amount', models.PositiveIntegerField(help_text="Amount in minor currency units (kobo/cents), matching Subscription's convention.")),
                ('provider_plan_id', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_pricing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPricingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('to_amount', models.PositiveIntegerField()),
                ('from_provider_plan_id', models.CharField(blank=True, max_length=40)),
                ('to_provider_plan_id', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_pricing_history_actions', to=settings.AUTH_USER_MODEL)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.premiumpricing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
