# Generated by Django 4.2.30 on 2026-07-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_normalize_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scripture_last_read_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='scripture_streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='scripture_streak_freeze_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='scripture_streak_freezes_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
