# Generated by Django 4.2.30 on 2026-08-26 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testimonies', '0015_audiouploadintent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10)),
                ('show_owner_name', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist')),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='testimonies.testimony')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['playlist', 'position'], name='playlistitem_playlist_pos_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'testimony'), name='uniq_playlist_testimony'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', '-created_at'], name='playlist_owner_created_idx'),
        ),
    ]
