# Generated by Django 4.2.30 on 2026-07-28 12:00

from django.db import migrations

# Seeds ProfileContentBlock with the exact copy that was previously hardcoded
# in the mobile app's about_policy_screen.dart / help_screen.dart, so making
# this content dashboard-editable doesn't blank out real, already-shipped
# copy on rollout -- the admin can now edit it, but nothing changes for
# users until they do.
ABOUT_US_BODY = (
    "Welcome to iTestified! This app is designed to share testimonies, "
    "inspire faith, and help build a supportive community.\n\n"
    "Our Mission\n"
    "To provide a safe space for users to post and discover life-changing testimonies.\n\n"
    "Key Features\n"
    "• Share text or video testimonies\n"
    "• Browse inspirational pictures\n"
    "• Support one another through giving\n"
    "• Track giving history and favorites"
)

TERMS_OF_USE_BODY = "\n\n".join(
    [
        "Last Updated: 28th April, 2025",
        "Welcome to iTestified. These Terms govern your access and use of this application.",
        "By using this app, you agree to provide accurate information and not misuse the service.",
        "You are responsible for all activity under your account and should keep credentials secure.",
        "We reserve the right to suspend accounts for harmful behavior, abuse, or policy violations.",
        "If you do not agree to these terms, please discontinue using the app.",
    ]
)

PRIVACY_POLICY_BODY = "\n\n".join(
    [
        "Introduction: iTestified respects your privacy and handles data responsibly.",
        "Personal Information: name, email, testimony uploads, and support interactions may be stored.",
        "How We Use Information: to operate the platform, personalize content, and improve reliability.",
        "Data Security: we apply technical and organizational measures to protect user information.",
        "Your Rights: you may request account updates or deletion according to applicable policies.",
        "Changes to this policy will be published in-app and become effective when posted.",
    ]
)

SEED_BODIES = {
    "about_us": ABOUT_US_BODY,
    "terms_of_use": TERMS_OF_USE_BODY,
    "privacy_policy": PRIVACY_POLICY_BODY,
}


def seed_content_blocks(apps, schema_editor):
    ProfileContentBlock = apps.get_model("profile_content", "ProfileContentBlock")
    for key, body in SEED_BODIES.items():
        ProfileContentBlock.objects.get_or_create(key=key, defaults={"body": body})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profile_content', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_content_blocks, noop),
    ]
