# Generated by Django 4.2.30 on 2026-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_content', '0002_seed_initial_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontentblock',
            name='key',
            field=models.CharField(choices=[('about_us', 'About Us'), ('terms_of_use', 'Terms of Use'), ('privacy_policy', 'Privacy Policy'), ('support_email', 'Support Email'), ('support_phone', 'Support Phone')], max_length=30, unique=True),
        ),
    ]
