# Generated by Django 4.2.30 on 2026-07-28 12:12

from django.db import migrations

# Seeds the real support contact info that replaced the fake placeholder
# values on the Help screen (Phase 7 post-completion review) -- these are
# still hardcoded in help_screen.dart today, so this seed is what makes
# Slice 5's dashboard edit start from the real, already-correct values
# rather than blanking them out on rollout.
SEED_BODIES = {
    "support_email": "ifnotgodtech@gmail.com",
    "support_phone": "+2348061464092",
}


def seed_support_contact(apps, schema_editor):
    ProfileContentBlock = apps.get_model("profile_content", "ProfileContentBlock")
    for key, body in SEED_BODIES.items():
        ProfileContentBlock.objects.get_or_create(key=key, defaults={"body": body})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profile_content', '0003_alter_profilecontentblock_key'),
    ]

    operations = [
        migrations.RunPython(seed_support_contact, noop),
    ]
