# Generated by Django 4.2.30 on 2026-07-28 12:24

from django.db import migrations

# Seeds the 4 FAQ entries that were previously hardcoded in
# help_screen.dart, in their existing order, so making this dashboard-
# editable doesn't blank out real, already-shipped content on rollout.
SEED_FAQS = [
    (
        "How do i post my testimonies?",
        "Use the + action from the bottom bar and complete the testimony form.",
    ),
    (
        "How can I donate to iTestified?",
        "Open Giving from profile and choose your preferred donation method.",
    ),
    (
        "How can I change the App's theme",
        "Open Profile > Display and choose dark or light mode.",
    ),
    (
        "How can I edit my profile information?",
        "Open Profile > Edit Profile and update your name, email, or image.",
    ),
]


def seed_help_faqs(apps, schema_editor):
    HelpFaqEntry = apps.get_model("profile_content", "HelpFaqEntry")
    if HelpFaqEntry.objects.exists():
        return
    for index, (question, answer) in enumerate(SEED_FAQS):
        HelpFaqEntry.objects.create(question=question, answer=answer, display_order=index)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profile_content', '0005_helpfaqentry'),
    ]

    operations = [
        migrations.RunPython(seed_help_faqs, noop),
    ]
