# Generated by Django 4.2.30 on 2026-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_content', '0006_seed_help_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontentblock',
            name='key',
            field=models.CharField(choices=[('about_us', 'About Us'), ('terms_of_use', 'Terms of Use'), ('privacy_policy', 'Privacy Policy'), ('support_email', 'Support Email'), ('support_phone', 'Support Phone'), ('referral_program_terms', 'Referral Program Terms')], max_length=30, unique=True),
        ),
    ]
