# Generated by Django 4.2.30 on 2026-08-18 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0013_translationjob_transcriptionjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaExportBrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True)),
                ('watermark_text', models.CharField(default='From iTestified', max_length=120)),
                ('call_to_action', models.CharField(default='Get the iTestified app for more inspiring testimonies.', max_length=255)),
                ('end_card_url', models.URLField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_media_export_branding_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'media export branding configuration',
                'verbose_name_plural': 'media export branding configuration',
            },
        ),
        migrations.CreateModel(
            name='BrandedVideoExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding_version', models.PositiveIntegerField()),
                ('source_video_url', models.URLField()),
                ('branded_video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_branded_video_exports', to=settings.AUTH_USER_MODEL)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branded_exports', to='testimonies.testimony')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-updated_at'], name='media_export_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='brandedvideoexport',
            constraint=models.UniqueConstraint(fields=('testimony', 'branding_version'), name='uniq_branded_export_testimony_branding'),
        ),
    ]
