# Generated by Django 4.2.30 on 2026-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandedvideoexport',
            name='branded_video_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='brandedvideoexport',
            name='source_video_url',
            field=models.URLField(max_length=2048),
        ),
    ]
