# Generated by Django 4.2.30 on 2026-07-29 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authn', '0002_alter_emailchallenge_purpose_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_using', "I don't use the app anymore"), ('privacy_concerns', 'I have privacy concerns'), ('new_account', "I'm creating a new account"), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
