from django.urls import path

from .views import (
    AdminCategoryActivationView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    CategoryFollowToggleView,
    AdminApproveTestimonyView,
    AdminPendingModerationQueueView,
    AdminRejectTestimonyView,
    AdminScheduleTestimonyView,
    AdminArchiveTestimonyView,
    AdminUpdateVideoTestimonyView,
    AdminUploadNowVideoTestimonyView,
    AdminTestimonyPullQuoteView,
    AdminTestimonyDetailView,
    AdminTestimonyListView,
    AdminTestimonyModerationHistoryView,
    AdminTranscriptionJobListView,
    AdminTranscriptionJobRetryView,
    AdminTranslationJobListView,
    AdminTranslationJobRetryView,
    AdminVideoTestimonyUploadSignatureView,
    AdminVideoTestimonyUploadView,
    AdminVideoTestimonyCreateFromUrlView,
    AdminDeleteTestimonyView,
    AuthenticatedDraftTestimonySubmitView,
    AuthenticatedMyTestimonyListView,
    AuthenticatedMyTestimonyDeleteView,
    AuthenticatedRejectedTestimonyResubmitView,
    AuthenticatedWrittenTestimonyCreateView,
    AudioUploadPolicyView,
    AuthenticatedAudioUploadSignatureView,
    AuthenticatedAudioTestimonyCreateView,
    AdminAudioUploadPolicyView,
    VideoUploadPolicyView,
    AuthenticatedVideoUploadSignatureView,
    AuthenticatedVideoTestimonyCreateView,
    AdminVideoUploadPolicyView,
    FavoriteListView,
    FavoriteTestimonyListView,
    FavoriteToggleView,
    ForYouTestimonyListView,
    HomeFeedView,
    PublicCategoryListView,
    PublicTestimonyDetailView,
    PublicTestimonyListView,
    PublicTestimonyShareView,
    PublicTestimonyViewIncrementView,
    TestimonyCommentDeleteView,
    TestimonyCommentListCreateView,
    TestimonyReactionView,
    TestimonyTranslationView,
)

urlpatterns = [
    path("categories/", PublicCategoryListView.as_view(), name="testimony-category-list"),
    path("categories/<int:category_id>/follow/", CategoryFollowToggleView.as_view(), name="testimony-category-follow-toggle"),
    path("", PublicTestimonyListView.as_view(), name="testimony-list"),
    path("<int:pk>/", PublicTestimonyDetailView.as_view(), name="testimony-detail"),
    path("<int:pk>/share/", PublicTestimonyShareView.as_view(), name="testimony-share"),
    path("<int:testimony_id>/view/", PublicTestimonyViewIncrementView.as_view(), name="testimony-view-increment"),
    path("mine/", AuthenticatedMyTestimonyListView.as_view(), name="testimony-mine-list"),
    path(
        "mine/<int:testimony_id>/resubmit/",
        AuthenticatedRejectedTestimonyResubmitView.as_view(),
        name="testimony-mine-resubmit",
    ),
    path(
        "mine/<int:testimony_id>/submit-draft/",
        AuthenticatedDraftTestimonySubmitView.as_view(),
        name="testimony-mine-submit-draft",
    ),
    path(
        "mine/<int:testimony_id>/",
        AuthenticatedMyTestimonyDeleteView.as_view(),
        name="testimony-mine-delete",
    ),
    path("for-you/", ForYouTestimonyListView.as_view(), name="testimony-for-you-feed"),
    path("home/feed/", HomeFeedView.as_view(), name="testimony-home-feed"),
    path("favorites/", FavoriteListView.as_view(), name="testimony-favorite-list"),
    path("favorites/feed/", FavoriteTestimonyListView.as_view(), name="testimony-favorite-feed"),
    path("<int:testimony_id>/favorite/", FavoriteToggleView.as_view(), name="testimony-favorite-toggle"),
    path("<int:testimony_id>/react/", TestimonyReactionView.as_view(), name="testimony-react"),
    path("<int:testimony_id>/comments/", TestimonyCommentListCreateView.as_view(), name="testimony-comment-list-create"),
    path("<int:testimony_id>/translations/", TestimonyTranslationView.as_view(), name="testimony-translations"),
    path("comments/<int:comment_id>/", TestimonyCommentDeleteView.as_view(), name="testimony-comment-delete"),
    path("submit/written/", AuthenticatedWrittenTestimonyCreateView.as_view(), name="testimony-submit-written"),
    path("audio-upload-policy/", AudioUploadPolicyView.as_view(), name="audio-upload-policy"),
    path("submit/audio/upload-signature/", AuthenticatedAudioUploadSignatureView.as_view(), name="testimony-submit-audio-signature"),
    path("submit/audio/", AuthenticatedAudioTestimonyCreateView.as_view(), name="testimony-submit-audio"),
    path("admin/audio-upload-policy/", AdminAudioUploadPolicyView.as_view(), name="admin-audio-upload-policy"),
    path("video-upload-policy/", VideoUploadPolicyView.as_view(), name="video-upload-policy"),
    path("submit/video/upload-signature/", AuthenticatedVideoUploadSignatureView.as_view(), name="testimony-submit-video-signature"),
    path("submit/video/", AuthenticatedVideoTestimonyCreateView.as_view(), name="testimony-submit-video"),
    path("admin/video-upload-policy/", AdminVideoUploadPolicyView.as_view(), name="admin-video-upload-policy"),
    path("admin/categories/", AdminCategoryListCreateView.as_view(), name="admin-testimony-category-list-create"),
    path("admin/categories/<int:pk>/", AdminCategoryDetailView.as_view(), name="admin-testimony-category-detail"),
    path(
        "admin/categories/<int:category_id>/activation/",
        AdminCategoryActivationView.as_view(),
        name="admin-testimony-category-activation",
    ),
    path("admin/testimonies/", AdminTestimonyListView.as_view(), name="admin-testimony-list"),
    path("admin/testimonies/upload-video/", AdminVideoTestimonyUploadView.as_view(), name="admin-testimony-upload-video"),
    path("admin/testimonies/upload-signature/", AdminVideoTestimonyUploadSignatureView.as_view(), name="admin-testimony-upload-signature"),
    path("admin/testimonies/create-video-from-url/", AdminVideoTestimonyCreateFromUrlView.as_view(), name="admin-testimony-create-video-from-url"),
    path("admin/testimonies/pending/", AdminPendingModerationQueueView.as_view(), name="admin-testimony-pending-queue"),
    path("admin/testimonies/<int:pk>/", AdminTestimonyDetailView.as_view(), name="admin-testimony-detail"),
    path("admin/testimonies/<int:testimony_id>/approve/", AdminApproveTestimonyView.as_view(), name="admin-testimony-approve"),
    path("admin/testimonies/<int:testimony_id>/reject/", AdminRejectTestimonyView.as_view(), name="admin-testimony-reject"),
    path("admin/testimonies/<int:testimony_id>/schedule/", AdminScheduleTestimonyView.as_view(), name="admin-testimony-schedule"),
    path("admin/testimonies/<int:testimony_id>/archive/", AdminArchiveTestimonyView.as_view(), name="admin-testimony-archive"),
    path("admin/testimonies/<int:testimony_id>/delete/", AdminDeleteTestimonyView.as_view(), name="admin-testimony-delete"),
    path("admin/testimonies/<int:testimony_id>/edit/", AdminUpdateVideoTestimonyView.as_view(), name="admin-testimony-edit-video"),
    path("admin/testimonies/<int:testimony_id>/pull-quote/", AdminTestimonyPullQuoteView.as_view(), name="admin-testimony-pull-quote"),
    path("admin/testimonies/<int:testimony_id>/upload-now/", AdminUploadNowVideoTestimonyView.as_view(), name="admin-testimony-upload-now-video"),
    path(
        "admin/testimonies/<int:testimony_id>/moderation-history/",
        AdminTestimonyModerationHistoryView.as_view(),
        name="admin-testimony-moderation-history",
    ),
    path(
        "admin/transcription-jobs/",
        AdminTranscriptionJobListView.as_view(),
        name="admin-transcription-job-list",
    ),
    path(
        "admin/transcription-jobs/<int:job_id>/retry/",
        AdminTranscriptionJobRetryView.as_view(),
        name="admin-transcription-job-retry",
    ),
    path(
        "admin/translation-jobs/",
        AdminTranslationJobListView.as_view(),
        name="admin-translation-job-list",
    ),
    path(
        "admin/translation-jobs/<int:job_id>/retry/",
        AdminTranslationJobRetryView.as_view(),
        name="admin-translation-job-retry",
    ),
]
