from django.urls import path

from .views import (
    AdminCategoryActivationView,
    AdminCategoryDetailView,
    AdminCategoryListCreateView,
    AdminApproveTestimonyView,
    AdminPendingModerationQueueView,
    AdminRejectTestimonyView,
    AdminScheduleTestimonyView,
    AdminArchiveTestimonyView,
    AdminUpdateVideoTestimonyView,
    AdminUploadNowVideoTestimonyView,
    AdminTestimonyDetailView,
    AdminTestimonyListView,
    AdminTestimonyModerationHistoryView,
    AdminVideoTestimonyUploadView,
    AdminVideoTestimonyCreateFromUrlView,
    AdminDeleteVideoTestimonyView,
    AuthenticatedMyTestimonyListView,
    AuthenticatedMyTestimonyDeleteView,
    AuthenticatedRejectedTestimonyResubmitView,
    AuthenticatedVideoTestimonyCreateView,
    AuthenticatedWrittenTestimonyCreateView,
    FavoriteListView,
    FavoriteTestimonyListView,
    FavoriteToggleView,
    PublicCategoryListView,
    PublicTestimonyDetailView,
    PublicTestimonyListView,
    PublicTestimonyViewIncrementView,
    TestimonyCommentDeleteView,
    TestimonyCommentListCreateView,
)

urlpatterns = [
    path("categories/", PublicCategoryListView.as_view(), name="testimony-category-list"),
    path("", PublicTestimonyListView.as_view(), name="testimony-list"),
    path("<int:pk>/", PublicTestimonyDetailView.as_view(), name="testimony-detail"),
    path("<int:testimony_id>/view/", PublicTestimonyViewIncrementView.as_view(), name="testimony-view-increment"),
    path("mine/", AuthenticatedMyTestimonyListView.as_view(), name="testimony-mine-list"),
    path(
        "mine/<int:testimony_id>/resubmit/",
        AuthenticatedRejectedTestimonyResubmitView.as_view(),
        name="testimony-mine-resubmit",
    ),
    path(
        "mine/<int:testimony_id>/",
        AuthenticatedMyTestimonyDeleteView.as_view(),
        name="testimony-mine-delete",
    ),
    path("favorites/", FavoriteListView.as_view(), name="testimony-favorite-list"),
    path("favorites/feed/", FavoriteTestimonyListView.as_view(), name="testimony-favorite-feed"),
    path("<int:testimony_id>/favorite/", FavoriteToggleView.as_view(), name="testimony-favorite-toggle"),
    path("<int:testimony_id>/comments/", TestimonyCommentListCreateView.as_view(), name="testimony-comment-list-create"),
    path("comments/<int:comment_id>/", TestimonyCommentDeleteView.as_view(), name="testimony-comment-delete"),
    path("submit/written/", AuthenticatedWrittenTestimonyCreateView.as_view(), name="testimony-submit-written"),
    path("submit/video/", AuthenticatedVideoTestimonyCreateView.as_view(), name="testimony-submit-video"),
    path("admin/categories/", AdminCategoryListCreateView.as_view(), name="admin-testimony-category-list-create"),
    path("admin/categories/<int:pk>/", AdminCategoryDetailView.as_view(), name="admin-testimony-category-detail"),
    path(
        "admin/categories/<int:category_id>/activation/",
        AdminCategoryActivationView.as_view(),
        name="admin-testimony-category-activation",
    ),
    path("admin/testimonies/", AdminTestimonyListView.as_view(), name="admin-testimony-list"),
    path("admin/testimonies/upload-video/", AdminVideoTestimonyUploadView.as_view(), name="admin-testimony-upload-video"),
    path("admin/testimonies/create-video-from-url/", AdminVideoTestimonyCreateFromUrlView.as_view(), name="admin-testimony-create-video-from-url"),
    path("admin/testimonies/pending/", AdminPendingModerationQueueView.as_view(), name="admin-testimony-pending-queue"),
    path("admin/testimonies/<int:pk>/", AdminTestimonyDetailView.as_view(), name="admin-testimony-detail"),
    path("admin/testimonies/<int:testimony_id>/approve/", AdminApproveTestimonyView.as_view(), name="admin-testimony-approve"),
    path("admin/testimonies/<int:testimony_id>/reject/", AdminRejectTestimonyView.as_view(), name="admin-testimony-reject"),
    path("admin/testimonies/<int:testimony_id>/schedule/", AdminScheduleTestimonyView.as_view(), name="admin-testimony-schedule"),
    path("admin/testimonies/<int:testimony_id>/archive/", AdminArchiveTestimonyView.as_view(), name="admin-testimony-archive"),
    path("admin/testimonies/<int:testimony_id>/delete/", AdminDeleteVideoTestimonyView.as_view(), name="admin-testimony-delete-video"),
    path("admin/testimonies/<int:testimony_id>/edit/", AdminUpdateVideoTestimonyView.as_view(), name="admin-testimony-edit-video"),
    path("admin/testimonies/<int:testimony_id>/upload-now/", AdminUploadNowVideoTestimonyView.as_view(), name="admin-testimony-upload-now-video"),
    path(
        "admin/testimonies/<int:testimony_id>/moderation-history/",
        AdminTestimonyModerationHistoryView.as_view(),
        name="admin-testimony-moderation-history",
    ),
]
