# Generated by Django 4.2.30 on 2026-08-18 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testimonies', '0013_translationjob_transcriptionjob_and_more'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_response', to='testimonies.testimonyreaction')),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_responses_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
