# Generated by Django 4.2.30 on 2026-08-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_prayerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
