# Generated by Django 4.2.30 on 2026-08-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_creatorprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
