# Generated by Django 4.2.30 on 2026-05-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('testimony_submitted', 'Testimony Submitted'), ('testimony_approved', 'Testimony Approved'), ('testimony_rejected', 'Testimony Rejected'), ('testimony_comment', 'Testimony Comment')], max_length=40),
        ),
    ]
