# Generated by Django 4.2.30 on 2026-07-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_new_video_testimony_notification_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['notification_type', 'is_read', '-created_at'], name='notif_type_read_idx'),
        ),
    ]
