# Generated by Django 4.2.30 on 2026-07-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreference',
            name='allow_push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
