# Generated by Django 4.2.30 on 2026-08-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('testimony_submitted', 'Testimony Submitted'), ('testimony_approved', 'Testimony Approved'), ('testimony_rejected', 'Testimony Rejected'), ('testimony_comment', 'Testimony Comment'), ('new_video_testimony', 'New Video Testimony'), ('donation_received', 'Donation Received'), ('app_update_available', 'App Update Available'), ('scripture_published', 'Scripture Published'), ('creator_digest', 'Creator Digest')], max_length=40),
        ),
    ]
