# Generated by Django 4.2.30 on 2026-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('testimony_submitted', 'Testimony Submitted'), ('testimony_approved', 'Testimony Approved'), ('testimony_rejected', 'Testimony Rejected'), ('testimony_comment', 'Testimony Comment'), ('new_video_testimony', 'New Video Testimony'), ('donation_received', 'Donation Received'), ('app_update_available', 'App Update Available'), ('scripture_published', 'Scripture Published'), ('creator_digest', 'Creator Digest'), ('prayer_response', 'Prayer Response'), ('live_broadcast_approval_requested', 'Live Broadcast Approval Requested'), ('live_broadcast_approval_decided', 'Live Broadcast Approval Decided'), ('live_broadcast_recording_ready', 'Live Broadcast Recording Ready')], max_length=40),
        ),
    ]
