# Generated by Django 4.2.30 on 2026-07-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversionconfig',
            name='latest_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
